//! Note-taking (plan 042): paper notes and highlights persisted as JSON
//! in the app data directory. Domain-scoped commands only — the webview
//! never gets a filesystem API, and notes never leave the device unless
//! the user exports them.

use std::collections::HashMap;
use std::fs;
use std::path::PathBuf;
use std::sync::{Mutex, OnceLock};

use serde::{Deserialize, Serialize};

use tauri::Manager;

const NOTES_FILE: &str = "notes.json";
/// Per-note cap: body + quote together stay under 50 KiB.
const MAX_NOTE_BYTES: usize = 50 * 1024;
/// File cap: 2 MiB of notes total (atomic rewrite, so a hard bound keeps
/// every save fast and bounded).
const MAX_FILE_BYTES: u64 = 2 * 1024 * 1024;
/// Upper bound on one import batch. `MAX_FILE_BYTES` with the smallest
/// realistic note (~200 B) allows a few thousand; this is the round number
/// well inside that, so the command rejects nonsense input before doing
/// any work rather than after.
const MAX_IMPORT_NOTES: usize = 5_000;

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct PaperNote {
    /// uuid v4, generated by the frontend.
    pub id: String,
    pub paper_id: String,
    /// Denormalized so the hub lists notes without re-fetching papers.
    pub paper_title: String,
    /// "note" | "highlight".
    pub kind: String,
    /// Markdown; for highlights, the user comment (may be empty).
    pub body: String,
    #[serde(default)]
    pub quote: Option<String>,
    /// 1-based page number when known.
    #[serde(default)]
    pub page: Option<u32>,
    pub created_at: String,
    pub updated_at: String,
    /// Max 5 short tags.
    #[serde(default)]
    pub tags: Vec<String>,
}

#[derive(Debug, Serialize, Deserialize)]
struct NotesFile {
    version: u32,
    notes: Vec<PaperNote>,
}

/// Where notes live. Test hook: PAPYRUS_NOTES_DIR overrides the app data
/// directory (tests cannot construct an AppHandle — same pattern as
/// citations.rs).
pub(crate) fn notes_path(app: Option<&tauri::AppHandle>) -> PathBuf {
    if let Some(dir) = crate::test_hooks::test_env("PAPYRUS_NOTES_DIR") {
        return PathBuf::from(dir).join(NOTES_FILE);
    }
    let dir = app
        .and_then(|a| a.path().app_local_data_dir().ok())
        .unwrap_or_else(|| std::env::temp_dir().join("papyrus"));
    dir.join(NOTES_FILE)
}

/// Reads the notes file. Corrupt JSON returns an empty list — never a
/// panic and never a crash loop on startup; the next save heals the file.
fn load_notes(path: &PathBuf) -> Vec<PaperNote> {
    let Ok(text) = fs::read_to_string(path) else {
        return Vec::new();
    };
    match serde_json::from_str::<NotesFile>(&text) {
        Ok(file) if file.version == 1 => file.notes,
        _ => Vec::new(),
    }
}

/// Atomic write: temp file + rename, so a crash mid-write can never
/// corrupt the only copy of the user's notes.
fn save_notes(path: &PathBuf, notes: &[PaperNote]) -> Result<(), String> {
    let body = serde_json::to_string(&NotesFile {
        version: 1,
        notes: notes.to_vec(),
    })
    .map_err(|e| format!("Cannot serialize notes: {e}"))?;
    if body.len() as u64 > MAX_FILE_BYTES {
        return Err("Notes storage is full (2 MiB cap)".into());
    }
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent).map_err(|e| format!("Cannot create the notes folder: {e}"))?;
    }
    let tmp = path.with_extension("tmp");
    fs::write(&tmp, body).map_err(|e| format!("Cannot write notes: {e}"))?;
    fs::rename(&tmp, path).map_err(|e| format!("Cannot save notes: {e}"))?;
    Ok(())
}

/// Field-level validation before anything touches disk. Unknown fields
/// in the incoming JSON are ignored by serde (no panic on extra data).
fn validate_note(note: &PaperNote) -> Result<(), String> {
    if note.id.trim().is_empty() || note.paper_id.trim().is_empty() {
        return Err("Note id and paper id are required".into());
    }
    if note.id.len() > 128 || note.paper_id.len() > 128 || note.paper_title.len() > 512 {
        return Err("Note fields are too long".into());
    }
    let quote_len = note.quote.as_deref().map_or(0, str::len);
    if note.body.len() + quote_len > MAX_NOTE_BYTES {
        return Err("Note is too large (50 KiB cap)".into());
    }
    match note.kind.as_str() {
        "note" => {}
        "highlight" => {
            if note.quote.as_deref().unwrap_or("").trim().is_empty() {
                return Err("A highlight needs a quote".into());
            }
        }
        _ => return Err("Unknown note kind".into()),
    }
    if note.tags.len() > 5 || note.tags.iter().any(|t| t.len() > 32) {
        return Err("Invalid tags".into());
    }
    Ok(())
}

#[tauri::command]
pub fn list_notes(app: tauri::AppHandle) -> Result<Vec<PaperNote>, String> {
    Ok(load_notes(&notes_path(Some(&app))))
}

/// Serializes the load-modify-save cycle (plan 046): two upserts racing
/// each other would otherwise both read the file, both write, and the
/// last writer would silently drop the other's note. The webview can
/// fire several upserts back to back (save highlight + add note).
fn notes_lock() -> &'static Mutex<()> {
    static NOTES_LOCK: OnceLock<Mutex<()>> = OnceLock::new();
    NOTES_LOCK.get_or_init(|| Mutex::new(()))
}

#[tauri::command]
pub fn upsert_note(app: tauri::AppHandle, note: PaperNote) -> Result<PaperNote, String> {
    validate_note(&note)?;
    let _guard = notes_lock().lock().unwrap_or_else(|p| p.into_inner());
    let path = notes_path(Some(&app));
    let mut notes = load_notes(&path);
    match notes.iter_mut().find(|n| n.id == note.id) {
        Some(existing) => *existing = note.clone(),
        None => notes.push(note.clone()),
    }
    save_notes(&path, &notes)?;
    Ok(note)
}

/// Merges an import batch into the stored notes, resolving same-id entries
/// by newer `updated_at`. Returns the merged list and how many notes the
/// batch actually changed. Pure, so it is tested without an AppHandle.
fn merge_import(current: Vec<PaperNote>, incoming: Vec<PaperNote>) -> (Vec<PaperNote>, usize) {
    // Deduplicate the batch first, keeping the newest per id. A HashMap
    // index keeps this linear: the old linear scan made the merge
    // quadratic, which is the very cost this command exists to remove.
    let mut winners: HashMap<String, PaperNote> = HashMap::with_capacity(incoming.len());
    for note in incoming {
        match winners.get(&note.id) {
            Some(existing) if existing.updated_at > note.updated_at => {}
            _ => {
                winners.insert(note.id.clone(), note);
            }
        }
    }

    // Merge into the stored list through the same index. `order` keeps the
    // existing notes in their original on-disk order (a rewrite must not
    // reshuffle the user's library) and appends genuinely new ids.
    // Keys are owned Strings: a `&str` borrowed from `current` cannot be
    // held while the vector is being mutated.
    let mut index: HashMap<String, usize> = HashMap::with_capacity(current.len() + winners.len());
    let mut order: Vec<PaperNote> = Vec::with_capacity(current.len() + winners.len());
    for note in current {
        if index.contains_key(&note.id) {
            continue; // unreachable duplicate already on disk
        }
        index.insert(note.id.clone(), order.len());
        order.push(note);
    }

    let mut applied = 0usize;
    for note in winners.into_values() {
        match index.get(&note.id) {
            Some(&at) => {
                if note.updated_at >= order[at].updated_at {
                    order[at] = note;
                    applied += 1;
                }
            }
            None => {
                index.insert(note.id.clone(), order.len());
                order.push(note);
                applied += 1;
            }
        }
    }
    (order, applied)
}

/// Applies a whole import in one load-modify-save cycle.
///
/// The webview used to replay every note through `upsert_note`, one
/// awaited IPC call per note. Each of those re-reads and re-writes the
/// entire notes file under the lock, so restoring a 500-note backup cost
/// 500 parses plus 500 atomic writes of a file that never stopped growing
/// (quadratic in the note count, and seconds of UI jank). Same-id notes
/// resolve by newer `updated_at`, matching the webview's merge rule.
#[tauri::command]
pub fn import_notes(app: tauri::AppHandle, notes: Vec<PaperNote>) -> Result<usize, String> {
    // Bound the batch before doing any work, and validate everything up
    // front so a bad entry cannot leave a half-applied import on disk.
    if notes.len() > MAX_IMPORT_NOTES {
        return Err(format!(
            "Import is too large (max {MAX_IMPORT_NOTES} notes)"
        ));
    }
    for note in &notes {
        validate_note(note)?;
    }

    let _guard = notes_lock().lock().unwrap_or_else(|p| p.into_inner());
    let path = notes_path(Some(&app));
    let (merged, applied) = merge_import(load_notes(&path), notes);
    save_notes(&path, &merged)?;
    Ok(applied)
}

#[tauri::command]
pub fn delete_note(app: tauri::AppHandle, id: String) -> Result<(), String> {
    if id.trim().is_empty() || id.len() > 128 {
        return Err("Invalid note id".into());
    }
    let _guard = notes_lock().lock().unwrap_or_else(|p| p.into_inner());
    let path = notes_path(Some(&app));
    let mut notes = load_notes(&path);
    notes.retain(|n| n.id != id);
    save_notes(&path, &notes)
}

#[cfg(test)]
mod tests {
    use super::*;

    /// The env var is process-global; serialize the tests that touch it.
    static ENV_LOCK: std::sync::Mutex<()> = std::sync::Mutex::new(());

    /// Exercises the raw load-modify-save cycle (the commands need an
    /// AppHandle), so the race regression runs against the same
    /// functions the commands wrap, under the same lock.
    fn raw_upsert(path: &PathBuf, note: &PaperNote) -> Result<(), String> {
        let _guard = notes_lock().lock().unwrap_or_else(|p| p.into_inner());
        let mut notes = load_notes(path);
        match notes.iter_mut().find(|n| n.id == note.id) {
            Some(existing) => *existing = note.clone(),
            None => notes.push(note.clone()),
        }
        save_notes(path, &notes)
    }

    fn temp_notes_dir(name: &str) -> PathBuf {
        std::env::temp_dir().join(format!("papyrus-notes-test-{name}-{}", std::process::id()))
    }

    fn sample_note(id: &str) -> PaperNote {
        PaperNote {
            id: id.to_string(),
            paper_id: "1706.03762".into(),
            paper_title: "Attention Is All You Need".into(),
            kind: "note".into(),
            body: "The multi-head attention insight is the key idea.".into(),
            quote: None,
            page: None,
            created_at: "2026-08-01T10:00:00Z".into(),
            updated_at: "2026-08-01T10:00:00Z".into(),
            tags: vec![],
        }
    }

    /// A sample note stamped at a given `updated_at`, for merge tests.
    fn note_at(id: &str, updated_at: &str) -> PaperNote {
        PaperNote {
            updated_at: updated_at.to_string(),
            body: format!("body-{id}"),
            ..sample_note(id)
        }
    }

    #[test]
    fn import_merge_adds_unknown_ids() {
        let (merged, applied) = merge_import(vec![sample_note("a")], vec![sample_note("b")]);
        assert_eq!(applied, 1);
        assert_eq!(merged.len(), 2);
        assert_eq!(merged[0].id, "a", "existing order is preserved");
        assert_eq!(merged[1].id, "b");
    }

    #[test]
    fn import_merge_takes_the_newer_copy_of_a_shared_id() {
        let (merged, applied) = merge_import(
            vec![note_at("a", "2026-01-01T00:00:00Z")],
            vec![note_at("a", "2026-02-01T00:00:00Z")],
        );
        assert_eq!(applied, 1);
        assert_eq!(merged.len(), 1);
        assert_eq!(merged[0].body, "body-a");
        assert_eq!(merged[0].updated_at, "2026-02-01T00:00:00Z");
    }

    #[test]
    fn import_merge_ignores_an_older_copy_of_a_shared_id() {
        // A re-import of an old backup must not clobber newer local edits.
        let (merged, applied) = merge_import(
            vec![note_at("a", "2026-02-01T00:00:00Z")],
            vec![note_at("a", "2026-01-01T00:00:00Z")],
        );
        assert_eq!(applied, 0, "nothing changed");
        assert_eq!(merged[0].updated_at, "2026-02-01T00:00:00Z");
    }

    #[test]
    fn import_merge_keeps_the_newest_duplicate_inside_one_batch() {
        // A file that lists the same id twice must land one note, the
        // newer one.
        let (merged, applied) = merge_import(
            vec![],
            vec![
                note_at("a", "2026-01-01T00:00:00Z"),
                note_at("a", "2026-03-01T00:00:00Z"),
                note_at("a", "2026-02-01T00:00:00Z"),
            ],
        );
        assert_eq!(merged.len(), 1);
        assert_eq!(applied, 1);
        assert_eq!(merged[0].updated_at, "2026-03-01T00:00:00Z");
    }

    #[test]
    fn import_merge_on_empty_library_adds_everything() {
        let incoming: Vec<PaperNote> = (0..500).map(|i| sample_note(&format!("n{i}"))).collect();
        let (merged, applied) = merge_import(vec![], incoming);
        assert_eq!(merged.len(), 500);
        assert_eq!(applied, 500);
    }

    #[test]
    fn import_merge_does_not_duplicate_stored_ids() {
        // Defensive: a pre-existing duplicate on disk collapses to one.
        let (merged, _) = merge_import(vec![sample_note("a"), sample_note("a")], vec![]);
        assert_eq!(merged.len(), 1);
    }

    #[test]
    fn round_trips_upsert_list_and_delete() {
        let _guard = ENV_LOCK.lock().unwrap_or_else(|p| p.into_inner());
        let dir = temp_notes_dir("roundtrip");
        let _ = fs::remove_dir_all(&dir);
        unsafe {
            std::env::set_var("PAPYRUS_NOTES_DIR", &dir);
        }

        let path = notes_path(None);
        // Upsert two notes (one highlight), then list them back.
        let mut highlight = sample_note("n1");
        highlight.kind = "highlight".into();
        highlight.quote = Some("we call it attention".into());
        highlight.page = Some(3);
        upsert_note_impl(&path, highlight.clone()).expect("upsert ok");
        upsert_note_impl(&path, sample_note("n2")).expect("upsert ok");

        let notes = load_notes(&path);
        assert_eq!(notes.len(), 2);
        let h = notes.iter().find(|n| n.id == "n1").expect("note present");
        assert_eq!(h.quote.as_deref(), Some("we call it attention"));
        assert_eq!(h.page, Some(3));

        // Upsert with the same id replaces (no duplicates).
        let mut updated = sample_note("n1");
        updated.body = "Rewritten.".into();
        upsert_note_impl(&path, updated).expect("upsert ok");
        let notes = load_notes(&path);
        assert_eq!(notes.len(), 2);
        assert_eq!(
            notes.iter().find(|n| n.id == "n1").unwrap().body,
            "Rewritten."
        );

        // Delete one.
        delete_note_impl(&path, "n2").expect("delete ok");
        let notes = load_notes(&path);
        assert_eq!(notes.len(), 1);
        assert_eq!(notes[0].id, "n1");

        let _ = fs::remove_dir_all(&dir);
        unsafe {
            std::env::remove_var("PAPYRUS_NOTES_DIR");
        }
    }

    /// The command body without the AppHandle (tests cannot construct one).
    fn upsert_note_impl(path: &PathBuf, note: PaperNote) -> Result<PaperNote, String> {
        validate_note(&note)?;
        let mut notes = load_notes(path);
        match notes.iter_mut().find(|n| n.id == note.id) {
            Some(existing) => *existing = note.clone(),
            None => notes.push(note.clone()),
        }
        save_notes(path, &notes)?;
        Ok(note)
    }

    fn delete_note_impl(path: &PathBuf, id: &str) -> Result<(), String> {
        let mut notes = load_notes(path);
        notes.retain(|n| n.id != id);
        save_notes(path, &notes)
    }

    #[test]
    fn corrupt_json_returns_empty_list() {
        let _guard = ENV_LOCK.lock().unwrap_or_else(|p| p.into_inner());
        let dir = temp_notes_dir("corrupt");
        let _ = fs::remove_dir_all(&dir);
        fs::create_dir_all(&dir).unwrap();
        fs::write(dir.join(NOTES_FILE), "not json {{{\n").unwrap();

        let notes = load_notes(&dir.join(NOTES_FILE));
        assert!(notes.is_empty(), "corrupt file must not panic or leak");

        // A wrong shape (not an object with notes) is treated the same.
        fs::write(dir.join(NOTES_FILE), r#"{"version":1,"notes":"oops"}"#).unwrap();
        assert!(load_notes(&dir.join(NOTES_FILE)).is_empty());

        let _ = fs::remove_dir_all(&dir);
        unsafe {
            std::env::remove_var("PAPYRUS_NOTES_DIR");
        }
    }

    #[test]
    fn rejects_oversized_notes() {
        let note = PaperNote {
            body: "x".repeat(MAX_NOTE_BYTES + 1),
            ..sample_note("big")
        };
        let err = validate_note(&note).expect_err("oversized note must be rejected");
        assert!(err.contains("50 KiB"), "got: {err}");

        let highlight = PaperNote {
            kind: "highlight".into(),
            body: "".into(),
            quote: Some("a quote".into()),
            ..sample_note("h")
        };
        assert!(
            validate_note(&highlight).is_ok(),
            "valid highlight accepted"
        );

        let empty_quote = PaperNote {
            kind: "highlight".into(),
            quote: Some("   ".into()),
            ..sample_note("h2")
        };
        let err = validate_note(&empty_quote).expect_err("empty quote rejected");
        assert!(err.contains("quote"), "got: {err}");
    }

    #[test]
    fn rejects_unknown_kind_and_bad_tags() {
        let err = validate_note(&PaperNote {
            kind: "scribble".into(),
            ..sample_note("x")
        })
        .expect_err("unknown kind rejected");
        assert!(err.contains("Unknown note kind"), "got: {err}");

        let err = validate_note(&PaperNote {
            tags: vec!["a".repeat(33)],
            ..sample_note("y")
        })
        .expect_err("long tag rejected");
        assert!(err.contains("Invalid tags"), "got: {err}");
    }

    #[test]
    fn rejects_missing_ids() {
        let err = validate_note(&PaperNote {
            id: "".into(),
            ..sample_note("z")
        })
        .expect_err("empty id rejected");
        assert!(err.contains("required"), "got: {err}");
    }

    #[test]
    fn concurrent_upserts_do_not_lose_notes() {
        // Two threads upsert DIFFERENT notes through the same locked
        // load-modify-save cycle the commands use. Before the lock,
        // the interleaved read-read-write-write dropped one of them.
        let _guard = ENV_LOCK.lock().unwrap_or_else(|p| p.into_inner());
        let dir = temp_notes_dir("concurrent");
        let _ = fs::remove_dir_all(&dir);
        unsafe {
            std::env::set_var("PAPYRUS_NOTES_DIR", &dir);
        }
        let path = notes_path(None);

        let a = sample_note("race-a");
        let b = sample_note("race-b");
        let path_a = path.clone();
        let path_b = path.clone();
        let t1 = std::thread::spawn(move || raw_upsert(&path_a, &a));
        let t2 = std::thread::spawn(move || raw_upsert(&path_b, &b));
        t1.join().unwrap().expect("first upsert ok");
        t2.join().unwrap().expect("second upsert ok");

        let notes = load_notes(&path);
        let ids: Vec<&str> = notes.iter().map(|n| n.id.as_str()).collect();
        assert!(
            ids.contains(&"race-a") && ids.contains(&"race-b"),
            "both notes must survive: {ids:?}"
        );

        let _ = fs::remove_dir_all(&dir);
        unsafe {
            std::env::remove_var("PAPYRUS_NOTES_DIR");
        }
    }
}
