//! Note-taking (plan 042): paper notes and highlights persisted as JSON
//! in the app data directory. Domain-scoped commands only — the webview
//! never gets a filesystem API, and notes never leave the device unless
//! the user exports them.

use std::fs;
use std::path::PathBuf;

use serde::{Deserialize, Serialize};

use tauri::Manager;

const NOTES_FILE: &str = "notes.json";
/// Per-note cap: body + quote together stay under 50 KiB.
const MAX_NOTE_BYTES: usize = 50 * 1024;
/// File cap: 2 MiB of notes total (atomic rewrite, so a hard bound keeps
/// every save fast and bounded).
const MAX_FILE_BYTES: u64 = 2 * 1024 * 1024;

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct PaperNote {
    /// uuid v4, generated by the frontend.
    pub id: String,
    pub paper_id: String,
    /// Denormalized so the hub lists notes without re-fetching papers.
    pub paper_title: String,
    /// "note" | "highlight".
    pub kind: String,
    /// Markdown; for highlights, the user comment (may be empty).
    pub body: String,
    #[serde(default)]
    pub quote: Option<String>,
    /// 1-based page number when known.
    #[serde(default)]
    pub page: Option<u32>,
    pub created_at: String,
    pub updated_at: String,
    /// Max 5 short tags.
    #[serde(default)]
    pub tags: Vec<String>,
}

#[derive(Debug, Serialize, Deserialize)]
struct NotesFile {
    version: u32,
    notes: Vec<PaperNote>,
}

/// Where notes live. Test hook: PAPYRUS_NOTES_DIR overrides the app data
/// directory (tests cannot construct an AppHandle — same pattern as
/// citations.rs).
fn notes_path(app: Option<&tauri::AppHandle>) -> PathBuf {
    if let Ok(dir) = std::env::var("PAPYRUS_NOTES_DIR") {
        return PathBuf::from(dir).join(NOTES_FILE);
    }
    let dir = app
        .and_then(|a| a.path().app_local_data_dir().ok())
        .unwrap_or_else(|| std::env::temp_dir().join("papyrus"));
    dir.join(NOTES_FILE)
}

/// Reads the notes file. Corrupt JSON returns an empty list — never a
/// panic and never a crash loop on startup; the next save heals the file.
fn load_notes(path: &PathBuf) -> Vec<PaperNote> {
    let Ok(text) = fs::read_to_string(path) else {
        return Vec::new();
    };
    match serde_json::from_str::<NotesFile>(&text) {
        Ok(file) if file.version == 1 => file.notes,
        _ => Vec::new(),
    }
}

/// Atomic write: temp file + rename, so a crash mid-write can never
/// corrupt the only copy of the user's notes.
fn save_notes(path: &PathBuf, notes: &[PaperNote]) -> Result<(), String> {
    let body = serde_json::to_string(&NotesFile {
        version: 1,
        notes: notes.to_vec(),
    })
    .map_err(|e| format!("Cannot serialize notes: {e}"))?;
    if body.len() as u64 > MAX_FILE_BYTES {
        return Err("Notes storage is full (2 MiB cap)".into());
    }
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent).map_err(|e| format!("Cannot create the notes folder: {e}"))?;
    }
    let tmp = path.with_extension("tmp");
    fs::write(&tmp, body).map_err(|e| format!("Cannot write notes: {e}"))?;
    fs::rename(&tmp, path).map_err(|e| format!("Cannot save notes: {e}"))?;
    Ok(())
}

/// Field-level validation before anything touches disk. Unknown fields
/// in the incoming JSON are ignored by serde (no panic on extra data).
fn validate_note(note: &PaperNote) -> Result<(), String> {
    if note.id.trim().is_empty() || note.paper_id.trim().is_empty() {
        return Err("Note id and paper id are required".into());
    }
    if note.id.len() > 128 || note.paper_id.len() > 128 || note.paper_title.len() > 512 {
        return Err("Note fields are too long".into());
    }
    let quote_len = note.quote.as_deref().map_or(0, str::len);
    if note.body.len() + quote_len > MAX_NOTE_BYTES {
        return Err("Note is too large (50 KiB cap)".into());
    }
    match note.kind.as_str() {
        "note" => {}
        "highlight" => {
            if note.quote.as_deref().unwrap_or("").trim().is_empty() {
                return Err("A highlight needs a quote".into());
            }
        }
        _ => return Err("Unknown note kind".into()),
    }
    if note.tags.len() > 5 || note.tags.iter().any(|t| t.len() > 32) {
        return Err("Invalid tags".into());
    }
    Ok(())
}

#[tauri::command]
pub fn list_notes(app: tauri::AppHandle) -> Result<Vec<PaperNote>, String> {
    Ok(load_notes(&notes_path(Some(&app))))
}

#[tauri::command]
pub fn upsert_note(app: tauri::AppHandle, note: PaperNote) -> Result<PaperNote, String> {
    validate_note(&note)?;
    let path = notes_path(Some(&app));
    let mut notes = load_notes(&path);
    match notes.iter_mut().find(|n| n.id == note.id) {
        Some(existing) => *existing = note.clone(),
        None => notes.push(note.clone()),
    }
    save_notes(&path, &notes)?;
    Ok(note)
}

#[tauri::command]
pub fn delete_note(app: tauri::AppHandle, id: String) -> Result<(), String> {
    if id.trim().is_empty() || id.len() > 128 {
        return Err("Invalid note id".into());
    }
    let path = notes_path(Some(&app));
    let mut notes = load_notes(&path);
    notes.retain(|n| n.id != id);
    save_notes(&path, &notes)
}

#[cfg(test)]
mod tests {
    use super::*;

    /// The env var is process-global; serialize the tests that touch it.
    static ENV_LOCK: std::sync::Mutex<()> = std::sync::Mutex::new(());

    fn temp_notes_dir(name: &str) -> PathBuf {
        std::env::temp_dir().join(format!("papyrus-notes-test-{name}-{}", std::process::id()))
    }

    fn sample_note(id: &str) -> PaperNote {
        PaperNote {
            id: id.to_string(),
            paper_id: "1706.03762".into(),
            paper_title: "Attention Is All You Need".into(),
            kind: "note".into(),
            body: "The multi-head attention insight is the key idea.".into(),
            quote: None,
            page: None,
            created_at: "2026-08-01T10:00:00Z".into(),
            updated_at: "2026-08-01T10:00:00Z".into(),
            tags: vec![],
        }
    }

    #[test]
    fn round_trips_upsert_list_and_delete() {
        let _guard = ENV_LOCK.lock().unwrap_or_else(|p| p.into_inner());
        let dir = temp_notes_dir("roundtrip");
        let _ = fs::remove_dir_all(&dir);
        unsafe {
            std::env::set_var("PAPYRUS_NOTES_DIR", &dir);
        }

        let path = notes_path(None);
        // Upsert two notes (one highlight), then list them back.
        let mut highlight = sample_note("n1");
        highlight.kind = "highlight".into();
        highlight.quote = Some("we call it attention".into());
        highlight.page = Some(3);
        upsert_note_impl(&path, highlight.clone()).expect("upsert ok");
        upsert_note_impl(&path, sample_note("n2")).expect("upsert ok");

        let notes = load_notes(&path);
        assert_eq!(notes.len(), 2);
        let h = notes.iter().find(|n| n.id == "n1").expect("note present");
        assert_eq!(h.quote.as_deref(), Some("we call it attention"));
        assert_eq!(h.page, Some(3));

        // Upsert with the same id replaces (no duplicates).
        let mut updated = sample_note("n1");
        updated.body = "Rewritten.".into();
        upsert_note_impl(&path, updated).expect("upsert ok");
        let notes = load_notes(&path);
        assert_eq!(notes.len(), 2);
        assert_eq!(
            notes.iter().find(|n| n.id == "n1").unwrap().body,
            "Rewritten."
        );

        // Delete one.
        delete_note_impl(&path, "n2").expect("delete ok");
        let notes = load_notes(&path);
        assert_eq!(notes.len(), 1);
        assert_eq!(notes[0].id, "n1");

        let _ = fs::remove_dir_all(&dir);
        unsafe {
            std::env::remove_var("PAPYRUS_NOTES_DIR");
        }
    }

    /// The command body without the AppHandle (tests cannot construct one).
    fn upsert_note_impl(path: &PathBuf, note: PaperNote) -> Result<PaperNote, String> {
        validate_note(&note)?;
        let mut notes = load_notes(path);
        match notes.iter_mut().find(|n| n.id == note.id) {
            Some(existing) => *existing = note.clone(),
            None => notes.push(note.clone()),
        }
        save_notes(path, &notes)?;
        Ok(note)
    }

    fn delete_note_impl(path: &PathBuf, id: &str) -> Result<(), String> {
        let mut notes = load_notes(path);
        notes.retain(|n| n.id != id);
        save_notes(path, &notes)
    }

    #[test]
    fn corrupt_json_returns_empty_list() {
        let _guard = ENV_LOCK.lock().unwrap_or_else(|p| p.into_inner());
        let dir = temp_notes_dir("corrupt");
        let _ = fs::remove_dir_all(&dir);
        fs::create_dir_all(&dir).unwrap();
        fs::write(dir.join(NOTES_FILE), "not json {{{\n").unwrap();

        let notes = load_notes(&dir.join(NOTES_FILE));
        assert!(notes.is_empty(), "corrupt file must not panic or leak");

        // A wrong shape (not an object with notes) is treated the same.
        fs::write(dir.join(NOTES_FILE), r#"{"version":1,"notes":"oops"}"#).unwrap();
        assert!(load_notes(&dir.join(NOTES_FILE)).is_empty());

        let _ = fs::remove_dir_all(&dir);
        unsafe {
            std::env::remove_var("PAPYRUS_NOTES_DIR");
        }
    }

    #[test]
    fn rejects_oversized_notes() {
        let note = PaperNote {
            body: "x".repeat(MAX_NOTE_BYTES + 1),
            ..sample_note("big")
        };
        let err = validate_note(&note).expect_err("oversized note must be rejected");
        assert!(err.contains("50 KiB"), "got: {err}");

        let highlight = PaperNote {
            kind: "highlight".into(),
            body: "".into(),
            quote: Some("a quote".into()),
            ..sample_note("h")
        };
        assert!(
            validate_note(&highlight).is_ok(),
            "valid highlight accepted"
        );

        let empty_quote = PaperNote {
            kind: "highlight".into(),
            quote: Some("   ".into()),
            ..sample_note("h2")
        };
        let err = validate_note(&empty_quote).expect_err("empty quote rejected");
        assert!(err.contains("quote"), "got: {err}");
    }

    #[test]
    fn rejects_unknown_kind_and_bad_tags() {
        let err = validate_note(&PaperNote {
            kind: "scribble".into(),
            ..sample_note("x")
        })
        .expect_err("unknown kind rejected");
        assert!(err.contains("Unknown note kind"), "got: {err}");

        let err = validate_note(&PaperNote {
            tags: vec!["a".repeat(33)],
            ..sample_note("y")
        })
        .expect_err("long tag rejected");
        assert!(err.contains("Invalid tags"), "got: {err}");
    }

    #[test]
    fn rejects_missing_ids() {
        let err = validate_note(&PaperNote {
            id: "".into(),
            ..sample_note("z")
        })
        .expect_err("empty id rejected");
        assert!(err.contains("required"), "got: {err}");
    }
}
